micronaut:
  application:
    name: ceUserRegistry

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.ce.userregistry.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

netty:
  default:
    allocator:
      max-order: 3
